settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: Isaac Menchaca # [First Name(s)] [Last Name]
  links:
    # S3 documents (Hospital docs)
    - https://test-rag-assistant.s3.us-east-1.amazonaws.com/PatientClinicalHistory.pdf
    # PubMed Articles
    - 